sonar.projectKey=ArnaudFlaesch_Dash-Web
sonar.organization=arnaudflaesch

sonar.projectName=Dash-Web
sonar.projectVersion=1.0

sonar.sources=src/app
sonar.sourceEncoding=UTF-8

sonar.exclusions=dist/**,nodes_modules/**,src/app/pipes/safe.pipe.ts
sonar.coverage.exclusions = "cypress/**", "/**/*.spec.ts"

sonar.css.stylelint.reportPaths=styleLintReport.json
