name: Node.js CI

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0

      - uses: actions/cache@v2
        with:
          path: |
            - ~/.npm
            - ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run eslint
          npm run lint:styles:report

      - name: Build
        run: |
          npm run build

      - name: Test
        run: npm run test

      - name: E2E Tests
        run: |
          npm i -g wait-on npm-run-all
          run-p -r npm run start npm run cy:run:parallel

      - name: Generate test report
        if: always()
        run: |
          mkdir cypress/screenshots || true
          npm run report:merge
          npm run report:generate
          npm run report:copyScreenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Cypress report
          path: cypress/reports/html

      - name: Send coverage report
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov 
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }} -F coverage-jest

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
